---
title: "Extended data figure 2"
author: "Marc J Williams"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: kable
    number_sections: yes
    toc: no
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
library(here)
source(here("src/setup.R"))

svcols <- signals:::SV_colors[c("Inversion", "Duplication", "Deletion", "Translocation")]
svcols[4] <- "grey70"

cell_table <- fread(paste0(config$root, "/metadata/cell_table.csv.gz"))  %>% 
      filter(is_normal == FALSE) %>% 
      filter(is_aberrant_normal_cell == FALSE) %>% 
      filter(is_s_phase_thresholds == FALSE) %>% 
      filter(is_doublet == "No") %>% 
      rename(patient = patient_id)
```

```{r, fig.height=4, fig.width=3.5}
ncells <- cell_table %>% 
  filter(patient %in% svs$patient) %>% 
  group_by(patient) %>% 
  summarize(ncells = n(), 
            pseudobulk_coverage = sum(coverage_depth),
            average_coverage = mean(coverage_depth)) %>% 
  ungroup() %>% 
  arrange(desc(ncells)) %>% 
  mutate(idx = 1:n()) 

gsv <- svs_md %>% 
  filter(patient %in% svs$patient) %>% 
  filter(target_idx %in% svs$target_idx) %>% 
  group_by(patient, Type) %>% 
  summarise(n = n()) %>% 
  mutate(ntot = sum(n)) %>% 
  arrange(patient) %>% 
  left_join(ncells) %>% 
  mutate(patient = str_remove(patient, "SPECTRUM-OV-")) %>% 
  ggplot(aes(x = fct_reorder(patient, ncells, .desc = T), y = n, fill = Type)) +
  geom_col(width = 0.5) +
  scale_fill_manual(values = svcols) +
  xlab("Patient") +
  ylab("# SVs") +
  xlab("") +
  labs(fill = "") +
  theme(legend.position = "inside", legend.position.inside = c(0.785, 0.8))

gcells <- ncells %>% 
  mutate(patient = str_remove(patient, "SPECTRUM-OV-")) %>% 
  ggplot(aes(x = fct_reorder(patient, ncells, .desc = T), y = ncells)) +
  geom_col(width = 0.5, col = "grey60", fill = "grey60") +
  xlab("Patient") +
  ylab("# cells") +
  xlab("")

gcoverage <- cell_table %>% 
  filter(patient   %in% svs$patient) %>% 
  left_join(ncells) %>% 
  mutate(patient = str_remove(patient, "SPECTRUM-OV-")) %>% 
  ggplot(aes(x = fct_reorder(patient, ncells, .desc = T), y = coverage_depth)) +
  geom_boxplot(width = 0.5, outlier.size = 0.05, fill = "grey70", size = 0.2, outlier.colour = "grey70") + 
  ylab("Coverage\nper cell")

gcoveragepb <- ncells %>% 
  mutate(patient = str_remove(patient, "SPECTRUM-OV-")) %>% 
  ggplot(aes(x = fct_reorder(patient, ncells, .desc = T), y = pseudobulk_coverage)) +
  geom_col(width = 0.5, col = "grey60", fill = "grey60") +
  xlab("Patient") +
  ylab("Pseudobulk\ncoverage") +
  xlab("")

gsvclonality <- svs %>% 
  filter(patient   %in% svs$patient) %>% 
  distinct(patient, target_idx, clonality) %>% 
  left_join(ncells) %>% 
  group_by(patient, clonality, ncells, idx) %>% 
  summarise(n = n()) %>% 
  ungroup() %>% 
  na.omit() %>% 
  mutate(patient = str_remove(patient, "SPECTRUM-OV-")) %>% 
  ggplot(aes(x = fct_reorder(patient, idx), y = n, fill = clonality)) +
  geom_col(position = position_dodge2(width = 0.9, preserve = "single"), width = 0.5) +
  scale_fill_manual(values = c("#A24936", "#0081A7"))+
  scale_color_manual(values = c("#A24936", "#0081A7")) +
  labs(fill = "") +
  xlab("") +
  ylab("# SVs") +
  theme(legend.position = "inside", legend.position.inside = c(0.785, 0.8))

plot_grid(gsvclonality + removexaxis,
          gsv + removexaxis,
          gcoverage + removexaxis,
          gcoveragepb + removexaxis,
          gcells + scale_x_discrete(guide = guide_axis(angle = 90)), 
          rel_heights = c(1,1,1,1,1.4),
          labels = letters[1:5], label_size = 8,
          ncol = 1, align = "v", axis = "lr") %>% 
   save_plot(here("Figures/EDF2_summary_svs_cells.pdf"), 
          ., base_width = 1 * 89 * 0.039, base_height = 4)

plot_grid(gsvclonality + removexaxis,
          gsv + removexaxis,
          gcoverage + removexaxis,
          gcoveragepb + removexaxis,
          gcells + scale_x_discrete(guide = guide_axis(angle = 90)), 
          rel_heights = c(1,1,1,1,1.4),
          labels = letters[1:5], label_size = 8,
          ncol = 1, align = "v", axis = "lr")

```

```{r}
ncells %>% 
  knitr::kable()

```

```{r}
ncells %>% 
  summarise(cells_mean = mean(ncells),
            cells_sum = sum(ncells),
            coverage_mean = mean(average_coverage)) 

cell_table %>% 
  filter(patient   %in% svs$patient) %>% 
  summarise(mean(coverage_depth), min(coverage_depth), max(coverage_depth),
            quantile(coverage_depth, 0.025))
```



```{r}
svs %>% 
  #.[to_keep == TRUE] %>% 
  distinct(patient, target_idx, clonality) %>% 
  left_join(ncells) %>% 
  group_by(patient, clonality, ncells, idx) %>% 
  summarise(n = n()) %>% 
  ungroup() %>% 
  na.omit() %>% 
  mutate(patient = str_remove(patient, "SPECTRUM-OV-")) %>%
  select(patient, clonality, n, ncells) %>% 
  pivot_wider(names_from = clonality, values_from = n) %>% 
  replace_na(list(SubClonal = 0)) %>% 
  mutate(total = Clonal + SubClonal) %>% 
  knitr::kable()

```

```{r}
x <- svs %>% 
  distinct(clonality, target_idx, patient, clone_id) %>% 
  mutate(clonality = ifelse(clone_id == "Clonal", "Clonal", "SubClonal")) %>% 
  left_join(ncells) %>% 
  group_by(patient, clonality, ncells, idx) %>% 
  summarise(n = n()) %>% 
  ungroup() %>% 
  na.omit() %>% 
  mutate(patient = str_remove(patient, "SPECTRUM-OV-")) %>%
  select(patient, clonality, n, ncells) %>% 
  pivot_wider(names_from = clonality, values_from = n) %>% 
  replace_na(list(SubClonal = 0)) %>% 
  mutate(total = Clonal + SubClonal) 
knitr::kable(x)

x %>% 
  filter(SubClonal > 0) %>% 
  summarize(mean(SubClonal), min(SubClonal), max(SubClonal))
```

## cfDNA coverage

```{r}
cov <- readxl::read_xlsx(config$tables, sheet = "S1 - Coverage") 
cov %>% 
  summarise(mean(mean_snv_counts_duplex), 
            mean(mean_sv_counts_uncollapsed_dedup),
            mean(mean_snv_counts_uncollapsed))
```

## Number of samples

```{r}
purity <- readxl::read_xlsx(config$tables, sheet = "S2 - Tumor Fractions") 

purity %>% 
  group_by(patient) %>% 
  summarize(nsample = n()) %>% 
  filter(patient %in% config$patients_timeline) %>% 
  summarise(mean(nsample), min(nsample), max(nsample))

```

## Recurrence

```{r}
recurrence <- readxl::read_xlsx(config$tables, sheet = "S12 - recurrence data") %>% 
  mutate(date = as.numeric(date))

left_join(purity, 
          recurrence %>% filter(recurrence_number == 1) %>%  select(patient_id, date) %>% rename(rec_date = date, patient = patient_id)) %>% 
  mutate(rec = days > rec_date) %>% 
select(patient, timepoint, days, tumorfraction_ClonalSV, ndetectedClonal_SV, tumorfraction_ClonalSNV, rec, rec_date) 
```
