---
title: "Extended data figure 5"
author: "Marc J Williams"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: kable
    number_sections: yes
    toc: no
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
source(here("src/setup.R"))
library(RColorBrewer)
```

## Error rates

Using the formula's in Zviran et al. Nature Genetics to calculate theoretical limits of detection and how they compare to error rates of our assay.

```{r}
source(here("src/lod.R"))
options(scipen = 999)
gevec <- c(10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000)
tfvec <- lapply(seq(0,7, 0.2), function(x) 10^-x) %>% unlist
Nvec <- c(1, 10, 100, 1000, 10000)
  
df1 <- data.frame()
for (ge in gevec){
    for (N in Nvec){
      for (tf in tfvec){
      df1 <- bind_rows(df1, data.frame(tf = tf, 
                                     ge = ge,
                                     N = N,
                                     R = ge*N,
                                     M = m_zviran(TF = tf, N = N, mu = 0.00, R = ge * N, cov = ge)))
    }
  }
}

breaks <- seq(0, 7, 1)
labels <- parse(text = paste0("10^-", breaks))

gprob <- df1 %>% 
  filter(N != 10000) %>% 
  mutate(M = ifelse(M > 1, 1, M)) %>% 
  mutate(tf_s = factor(tf, levels = rev(tfvec))) %>% 
  mutate(ge_s = factor(ge, levels = gevec)) %>% 
  mutate(Ns = paste("# muts. = ", N)) %>% 
  ggplot( aes(y = tf_s, x = ge_s, fill = M)) +
  geom_tile() +
  #scale_x_log10() +
  #scale_y_log10() +
  scale_fill_gradientn(colors = brewer.pal(9, "Blues")) +
  #scale_fill_viridis_c() +  # using viridis color palette (optional)
  # scale_fill_gradient2(
  #   low = "#053061",     # deep blue
  #   mid = "gray90",     # white
  #   high = "#67001f",    # deep red
  #   midpoint = 0.5
  # ) +
  theme_minimal(base_size = 8) +
  labs(y = "Tumor fraction", x = "Coverage", fill = "Detection\nprobability") +
  facet_wrap(~Ns, ncol = 4) +
  scale_y_discrete(
    breaks = paste0(10^(-seq(0, 7, 1))),
    labels = parse(text = paste0("10^-", seq(0, 7, 1)))
  ) +
  theme(panel.border = element_blank(),
            strip.background = element_blank(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            axis.line = element_blank(),
            legend.key.width = unit(0.25, "cm")) +
  scale_x_discrete(guide = guide_axis(angle = 45))

gprob
```

```{r}
options(scipen = 999)
#gevec <- c(20, 50, 100, 500, 1000, 2000, 5000, 10000)
Nvec <- c(seq(1,10,1), seq(50, 1000, 25), 10000)
Nvec <- c(1,2,5,10,50,100,500,1000,5000,10000)

gevec <- c(100, 1000, 10000)
Nvec <- c(seq(1, 10000,1))
  
df <- data.frame()
for (ge in gevec){
  print(ge)
    for (N in Nvec){
      df <- bind_rows(df, data.frame(tf = tlod(cov = ge, N = N), ge = ge, N = N))
  }
}

```


```{r}
error_rates <- readxl::read_xlsx(config$tables, sheet = "S6 - Error rates & LOD") %>% 
  group_by(bamtype, mutation_type) %>% 
  summarize(alt_counts = sum(alt_counts),
            total_counts = sum(total_counts)) %>% 
  ungroup() %>% 
  mutate(error = alt_counts / total_counts)
error_rates$Bamtype <- lapply(error_rates$bamtype, stringr::str_to_title) %>% unlist()
for_labs <- filter(error_rates, Bamtype != "Simplex")

new_labels <- c(
    "Uncollapsed" = "Uncorrected",
    "Duplex" = "Duplex"
)

g2 <- df %>% 
  filter(ge %in% c(100, 1000, 10000)) %>% 
  mutate(Coverage = paste0(ge)) %>% 
  ggplot(aes(y = tf, x = N)) +
  geom_line(aes(col = Coverage)) +
  #geom_point() ++
  geom_text( data = for_labs,  aes(x = 7000, y = 2 * error, label = paste0(mutation_type , ""), col = mutation_type), size = 2) +
  facet_wrap(~Bamtype, scales = "free", labeller = labeller(Bamtype = new_labels)) +
  logyscale(sigma = 10^-8) +
  geom_hline(data = for_labs, aes(yintercept = error, col = mutation_type), lty = 2) +
  scale_x_log10(breaks = c(1, 10, 100, 1000, 10000)) +
  xlab("Number of mutations") +
  ylab("cfDNA tumor fraction theoretical limit") + 
  theme(
    strip.background = element_blank(),
    panel.background = element_blank(),
    panel.spacing = unit(1, "cm"),
    axis.line = element_line(color = "black")
) +
  scale_color_manual(values = c(brewer.pal(9, "Reds")[c(3,6,9)], c("grey60", "grey60")))

g2

```

```{r}
gsave <- plot_grid(gprob, 
          plot_grid(NULL, g2, NULL, ncol = 3, rel_widths = c(0.2,1,0.2)), ncol = 1,
          labels = c("a", "b"), label_size = 8)

save_plot(plot = gsave, filename = here("Figures/EDF5_lod.pdf"),
          base_height = 4, base_width = config$default_plot_size$width)
```
