---
title: "Extended data figure 6"
author: "Marc J Williams"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: kable
    number_sections: yes
    toc: no
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Setup

```{r}
library(here)
source(here("src/setup.R"))
library(grid)
library(ComplexHeatmap)
#source(here("src/cfdna_utils.R"))
```

## Generate all heatmaps

```{r}
samples <- str_remove(config$patients_timeline, "SPECTRUM-OV-")
cp <- config$clonecols
names(cp) <- LETTERS[1:length(cp)]
glist <- list()
chroms <- c(paste0(1:11), "13", "15", "17", "20", "X")

ncells <- data.frame()

for (mysample in samples){
  print(mysample)
  
  clones <- read_allfiles("clones.csv", patient = mysample) %>% 
    filter(clone_id != "0") %>% 
    select(cell_id, clone_id)
  merge_clones <- fread(here("data/merge_clones.csv")) %>% filter(str_detect(patient, mysample))
  if (nrow(merge_clones) > 0){
    clones <- clones %>% 
      left_join(merge_clones) %>% 
      mutate(clone_id = ifelse(is.na(new_clone), clone_id, new_clone)) %>% 
      select(-new_clone) %>% 
      select(-patient)
  }
  # if (mysample == "044"){
  #   clones <- filter(clones, !str_detect(cell_id, "OMEN"))
  #   clones <- clones %>% 
  #     mutate(clone_id = ifelse(clone_id == "E", "E", "B"))
  # }
  cn <- read_allfiles("hscn.csv.gz", patient = mysample) %>% 
    filter(chr != "Y") %>% 
    filter(cell_id %in% clones$cell_id)
  tree <- ape::read.tree(find_allfiles(config$root, pattern = "newick", patient = mysample))
  
  ncells <- bind_rows(ncells, data.frame(ncells = nrow(clones), patient = mysample))
  
  my_title = paste0("Patient ", mysample, ", ", nrow(clones), " cells")
  pdf(here(paste0("Figures/Heatmaps/", mysample, "_heatmap.pdf")), 
      w = 89 * 0.039,
      h = 2)
  p <- plotHeatmap(cn,
              column_title = my_title,
              clone_pal = cp,
              column_title_gp = gpar(fontsize = 7),
              linkheight = 2,
              chrlabels = chroms,
              show_heatmap_legend = F,
              plotfrequency = F, 
              #frequency_height = 0.3,
              anno_width = 0.1,
              annofontsize = 6,
              show_legend = F,
              show_clone_text = F,
              show_library_label = F,
              tree = tree,
              plottree = T,
              reorderclusters = T,
              clusters = clones,
              tree_width = 1.6)
  print(p)
  glist[[mysample]] <- grid.grabExpr(draw(p), width = 89 * 0.039, height = 2)
  dev.off()
}

```

## Generate final figures

```{r}
glist %>% 
  cowplot::plot_grid(plotlist = ., ncol = 3) %>% 
  cowplot::plot_grid(., NULL, ncol = 1, rel_heights = c(1, 0.05)) %>% 
  cowplot::save_plot(plot = .,
            filename = here("Figures/EDF6.pdf"), 
            base_height = 10,
            base_width = 2 * 89 * 0.039)

glist %>% 
  cowplot::plot_grid(plotlist = ., ncol = 4) %>% 
  cowplot::plot_grid(., NULL, ncol = 1, rel_heights = c(1, 0.05)) %>% 
  cowplot::save_plot(plot = .,
            filename = here("Figures/Heatmaps/AllHeatmapsWide.pdf"), 
            base_height = 6,
            base_width = 2 * 89 * 0.039)

```

```{r, fig.height = 7, fig.width = 10.5}
glist %>% 
  cowplot::plot_grid(plotlist = ., ncol = 4) %>% 
  cowplot::plot_grid(., NULL, ncol = 1, rel_heights = c(1, 0.05)) 
```

```{r}
samples_all <- str_remove(config$patients, "SPECTRUM-OV-")
ncells <- read_allfiles("clones.csv", patient = samples_all) %>% 
  select(patient, cell_id, clone_id) %>% 
  group_by(patient) %>% 
  summarize(ncells = n())

DT::datatable(ncells, filter = "top")
```

```{r}
ncells %>% 
  summarize(total = sum(ncells), mean_cells = mean(ncells), min = min(ncells), max = max(ncells))

```