---
title: "Figure 1"
author: "Marc J Williams"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    df_print: kable
    number_sections: yes
    toc: no
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(here)
source(here("src/setup.R"))
library(grid)
library(ComplexHeatmap)
```

## Heatmap

```{r, fig.width = 7, fig.height = 2}
mysample <- "004"
clones <- read_allfiles("clones.csv", patient = mysample) %>% 
  filter(clone_id != "0") %>% 
  select(cell_id, clone_id)
cn <- read_allfiles("hscn.csv.gz", patient = mysample) %>% 
  filter(chr != "Y") %>% 
  filter(cell_id %in% clones$cell_id)
tree <- ape::read.tree(find_allfiles(config$root, pattern = "newick", patient = mysample))
cp <- config$clonecols
names(cp) <- LETTERS[1:length(cp)]
chroms <- c(paste0(1:18), "21", "X")

p <- plotHeatmap(cn,
                 str_to_remove = "SPECTRUM-OV-004_S1_",
                #column_title = my_title,
                clone_pal = cp,
                column_title_gp = gpar(fontsize = 7),
                linkheight = 2,
                chrlabels = chroms,
                show_heatmap_legend = F,
                plotfrequency = F, 
                #frequency_height = 0.3,
                anno_width = 0.1,
                annofontsize = 6,
                show_legend = T,
                show_clone_text = T,
                show_library_label = T,
                tree = tree,
                plottree = T,
                reorderclusters = T,
                clusters = clones,
                tree_width = 1.6)

p_g <- grid.grabExpr(draw(p), width = 2 * 89 * 0.039, height = 2)
plot_grid(p_g)
```

## Chr17

```{r, fig.width =3.471, fig_height = 2}
dat_10kb <- read_allfiles(pattern = "_clone_copynumber_10kb.csv", "004") %>% 
  mutate(cell_id = clone_id) %>% 
  filter(mappability > 0.99)

diff <- dat_10kb %>% 
  filter(cell_id %in% c("A", "B")) %>% 
  select(cell_id, chr, start, end, copy) %>% 
  pivot_wider(names_from = "cell_id", values_from = "copy") %>% 
  mutate(delta = A - B)

gchr17_A <- plotCNprofile(dat_10kb, 
              cellid = "A", 
              chrfilt = c("17"), 
              ideogram = T,
              maxCN = 10,
              pointsize = 0.1,
              y_axis_trans = "squashy",
              #SV = sv_to_plot,
              annotateregions = data.frame(chr = "17", start = 7565097),
              ) +
  theme_cowplot(font_size = 7, line_size = 0.25) +
  theme(legend.position = "none")


gchr17_B <- plotCNprofile(dat_10kb, 
              cellid = "B", 
              chrfilt = c("17"), 
              ideogram = T,
              maxCN = 10,
              pointsize = 0.1,
              y_axis_trans = "squashy",
              #SV = sv_to_plot,
              annotateregions = data.frame(chr = "17", start = 7565097),
              ) +
  theme_cowplot(font_size = 7, line_size = 0.25) +
  theme(legend.position = "none")


(gchr17 <- plot_grid(gchr17_A + removexaxis, 
          gchr17_B, 
          ncol = 1))
```


```{r, fig.width =3.471, fig_height = 0.5}
(chr17_diff <- diff %>% 
  filter(chr == "17") %>% 
  ggplot(aes(x = start, y = delta)) +
  geom_bar(stat = "identity"))

```


## Chr8

```{r, fig.width =7, fig_height = 2}

gchr8_A <- plotCNprofile(dat_10kb, 
              cellid = "A", 
              chrfilt = c("8"), 
              ideogram = T,
              maxCN = 10,
              pointsize = 0.1,
              y_axis_trans = "squashy",
              tickwidth = 25
              ) +
  theme_cowplot(font_size = 7, line_size = 0.25) +
  theme(legend.position = "none")


gchr8_B <- plotCNprofile(dat_10kb, 
              cellid = "B", 
              chrfilt = c("8"), 
              ideogram = T,
              maxCN = 10,
              pointsize = 0.1,
              y_axis_trans = "squashy",
              tickwidth = 25
              ) +
  theme_cowplot(font_size = 7, line_size = 0.25) +
  theme(legend.position = "none")


(gchr8<- plot_grid(gchr8_A + removexaxis, 
          gchr8_B, 
          ncol = 1))
```


```{r, fig.width =6, fig_height = 0.5}
(chr8_diff <- diff %>% 
  filter(chr == "8") %>% 
  ggplot(aes(x = start, y = delta)) +
  geom_bar(stat = "identity"))

```

## Final figure


```{r, fig.width = 7, fig.height = 5}
gfinal <- plot_grid(p_g,
                    plot_grid(gchr17, NULL, ncol = 2, labels = c("b", "c"), label_size = 7),
                    gchr8, 
                    labels = c("a", "", "c"), 
                    label_size = 7, 
                    ncol = 1,
                    rel_heights = c(1,1,1))

save_plot(plot = gfinal, filename = here("Figures/Fig1_OV-004.pdf"),
          base_width = 2 * 89 * 0.039, base_height = 5)
gfinal
```

## EDF4


```{r, fig.width = 7, fig.height = 4}
cn_clones <- consensuscopynumber(cn, clones)


g1 <- plotCNprofile(cn_clones, 
              cellid = "A", 
              chrfilt = c("8", "19"), 
              ideogram = T,
              maxCN = 15,
              pointsize = 2,
              y_axis_trans = "squashy",
              #SV = sv_to_plot,
              annotateregions = data.frame(chr = "17", start = 7565097),
              ) +
  theme_cowplot(font_size = 7, line_size = 0.25) +
  theme(legend.position = "none") +
  ggtitle("500kb bins")


g2 <- plotCNprofile(dat_10kb, 
              cellid = "A", 
              chrfilt = c("8", "19"), 
              ideogram = T,
              maxCN = 15,
              pointsize = 0.1,
              y_axis_trans = "squashy",
              #SV = sv_to_plot,
              annotateregions = data.frame(chr = "17", start = 7565097),
              ) +
  theme_cowplot(font_size = 7, line_size = 0.25) +
  theme(legend.position = "none") +
  ggtitle("10kb bins")

plot_grid(g1, g2, NULL, ncol = 1) %>% 
  save_plot(., filename = here("Figures/EDF4.pdf"),
          base_width = 2 * 89 * 0.039, base_height = 4)


plot_grid(g1, g2, NULL, ncol = 1)
```

