---
title: "Figure 5"
author: "Marc J Williams"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: kable
    number_sections: yes
    toc: no
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.height = 5)
```

## Setup

```{r}
library(here)
source(here("src/setup.R"))
source(here("src/tree_utils.R"))
source(here("src/copynumber_profile_plots.R"))
library(Seurat)
library(RColorBrewer)
cloneColors <- config$clonecols
names(cloneColors) <- LETTERS[1:length(cloneColors)]


cp <- config$clonecols
names(cp) <- LETTERS[1:length(cp)]
symnum.args <- list(cutpoints = c( 0.00, 0.001, 0.01, 0.05, 1), symbols = c("***", "**", "*", "ns"))

myrnaplot <- function(obj, feature, mycomparisons = NULL, myylab = "", add_compare = TRUE, usenquo = TRUE, filterclones = NULL){
  symnum.args <- list(cutpoints = c( 0.00, 0.001, 0.01, 0.05, 1), symbols = c("***", "**", "*", "ns"))
  clonecols <- config$clonecols
  names(clonecols) <- LETTERS[1:length(clonecols)]
  #obj@meta.data$featurex <- as.vector(obj@meta.data[feature])
  if(usenquo == FALSE) {
    # If feature is a string, use sym() to convert it to a symbol
    y_var <- rlang::sym(feature)
  } else {
    # If feature is already a variable/symbol, use enquo()
    y_var <- rlang::enquo(feature)
  }
  
  if (is.null(filterclones)){
    filterclones <- unique(obj@meta.data$clone_id)
  }
  
  test_data <- obj@meta.data %>% 
    filter(clone_id %in% mycomparisons[[1]])
  
  if(usenquo == FALSE) {
    t.test(test_data[[feature]] ~ test_data$clone_id) %>% print()
  } else {
    # Handle the enquo case if needed
    feature_name <- rlang::as_name(rlang::enquo(feature))
    t.test(test_data[[feature_name]] ~ test_data$clone_id) %>% print()
  }
  
  gg <- obj@meta.data %>% 
    filter(clone_id %in% filterclones) %>% 
    ggplot(aes(x = clone_id, y = !!y_var, fill = clone_id, col = clone_id)) +
    geom_violin(scale = "width",  alpha = 0.4, size = 0.2) +
    #geom_jitter(height = 0, width = 0.1, size = 0.3, alpha = 0.8) +
    geom_boxplot(outlier.colour = NA, color = "white", alpha = 0.8, size = 0.1, width = 0.28) +
    xlab("") +
    scale_fill_manual(values = clonecols) +
    scale_color_manual(values = clonecols) +
    theme(legend.position = "none") +
    ylab(myylab) 
  if (add_compare == TRUE){
    gg <- gg +
        ggpubr::stat_compare_means(label.y.npc = c(0.2),
                               method = "t.test",
                               aes(label = paste0(..p.signif..)), 
                               size = 2.5, symnum.args = symnum.args,
                               comparisons = mycomparisons)
  }
  return(gg)
}

mydnageneplot <- function(cn, clones, mygene, myylab = NULL, comps = list(c("A", "B")), filterclones = NULL){
  symnum.args <- list(cutpoints = c( 0.00, 0.001, 0.01, 0.05, 1), symbols = c("***", "**", "*", "ns"))
  cp <- config$clonecols
  names(cp) <- LETTERS[1:length(cp)]
  
  if (is.null(myylab)){
    myylab <- paste0(mygene, " CN")
  }
  genedf <- gene_copynumber(cn, mygene) %>% 
  left_join(clones)
  
  if (is.null(filterclones)){
    filterclones <- unique(obj@meta.data$clone_id)
  }
  
  genedf %>% 
    filter(clone_id %in% comps[[1]]) %>% 
    t.test(copy ~ clone_id, data = .) %>% 
    print()
  
  gdna <- genedf %>% 
      filter(clone_id != "0") %>% 
      filter(clone_id %in% filterclones) %>% 
      ggplot(aes(x = clone_id, y = copy, fill = clone_id, col = clone_id)) +
      geom_violin(scale = "width",  alpha = 0.4, size = 0.025) +
      geom_boxplot(outlier.colour = NA, color = "white", alpha = 0.8, size = 0.1, width = 0.28) +
      #geom_jitter(height = 0, width = 0.1, size = 0.3, alpha = 0.8) +
      xlab("") +
      scale_fill_manual(values = cp) +
      scale_color_manual(values = cp) +
      theme(legend.position = "none") +
      ylab(myylab) +
      ggpubr::stat_compare_means(label.y.npc = 0.9,
                                 method = "t.test",
                                 aes(label = paste0(..p.signif..)), 
                                 size = 2.5, symnum.args = symnum.args,
                                 comparisons = comps)
  return(gdna)
}

pointsizefunc <- function(w){
  0.001 * 250 / w
}
```


## OV-107

```{r}
obj <- readRDS(find_allfiles(".Rdata", patients = "107"))
obj <- subset(obj, subset = clone_id_clone_acn_10kb != "0")
#obj@meta.data$NOTCH3 <- as.vector(obj@assays$RNA$data["NOTCH3",])
obj@meta.data$NOTCH3 <- as.vector(obj@assays$RNA@data["NOTCH3",])
obj@meta.data$CCNE1 <- as.vector(obj@assays$RNA@data["CCNE1",])
obj@meta.data$HIF1A <- as.vector(obj@assays$RNA@data["HIF1A",])

obj@meta.data <- obj@meta.data %>% 
  mutate(for_test =
           case_when(
             clone_id_clone_acn_10kb %in% c("C", "D") ~ "C&D",
             clone_id_clone_acn_10kb %in% c("A", "B") ~ "A&B",
             TRUE ~ "Other"
           ))
obj@meta.data$clone_id <- obj@meta.data$clone_id_clone_acn_10kb
Idents(obj) <- "clone_id"

hallmark_pathways <- colnames(obj@meta.data)
hallmark_pathways <- hallmark_pathways[str_detect(hallmark_pathways, "pathway")]

mat <- obj@meta.data[, c("clone_id", hallmark_pathways)] %>% 
  pivot_longer(-clone_id) %>% 
  mutate(name = str_remove(name, ".pathway")) %>% 
  group_by(clone_id, name) %>%
  summarise(avg = mean(value)) %>% 
  spread(name, avg) %>% 
    data.frame(row.names = 1, check.names = FALSE, stringsAsFactors = FALSE) 

library(pheatmap)
hm1 <- pheatmap(t(mat[,-1]),fontsize=14, 
                        fontsize_row = 10, 
                        #color=myColor, breaks = progenyBreaks, 
                        angle_col = 0,
                        treeheight_col = 0,  border_color = NA)

plot_grid(hm1$gtable)
```

```{r, fig.height = 3}
mysample <- "107"

print("NOTCH3")
gnotch <- myrnaplot(obj, feature = NOTCH3, 
          mycomparisons = list( c("A", "D")),
          myylab = "NOTCH3")

print("HIF1A")
ghif1a <- myrnaplot(obj, feature = HIF1A, 
          mycomparisons = list( c("A", "D")),
          myylab = "HIF1A")

print("VEGF")
gvegf <- myrnaplot(obj, feature = VEGF.pathway, 
          mycomparisons = list( c("A", "D")),
          myylab = "VEGF")

print("Hypoxia")
ghypoxia <- myrnaplot(obj, feature = Hypoxia.pathway, 
          mycomparisons = list( c("A", "D")),
          myylab = "Hypoxia")

print("Hypoxia 2")  
ghypoxia <- myrnaplot(obj, feature = HALLMARK_HYPOXIA, 
          mycomparisons = list( c("A", "D")),
          myylab = "Hypoxia")

print("G2M")
gG2m <- myrnaplot(obj, feature = HALLMARK_G2M_CHECKPOINT, 
          mycomparisons = list( c("A", "D")),
          myylab = "G2M")

print("EMT")
gemt <- myrnaplot(obj, feature = EMT.module, 
          mycomparisons = list( c("A", "D")),
          myylab = "EMT")

gumap1_107 <- DimPlot(obj, group.by =  "clone_id", cols = cp, alpha = 0.5, pt.size = 0.5, stroke.size = 0, raster = FALSE, shuffle = TRUE) + ggtitle("") +
  theme_void() +
  theme(legend.position = "bottom") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  guides(color=guide_legend(nrow=2, byrow=TRUE, override.aes = list(size=1)))  
libcols <- c("#A1C181", "#BBA0B2", "#D58936", "#1985A1" , "firebrick4", "yellow3", "magenta")
gumap2_107 <- DimPlot(obj, group.by =  "sample_short", cols = libcols, alpha = 0.5, pt.size = 0.5, stroke.size = 0, raster = FALSE, shuffle = TRUE) + ggtitle("") +
  theme_void() +
  theme(legend.position = "bottom") +
  guides(color=guide_legend(nrow=2, byrow=TRUE, override.aes = list(size=1))) 
cowplot::plot_grid(gumap2_107, gumap1_107, ncol = 2, align = "hv", axis = "tb") %>% 
  save_plot(plot = ., filename = here("Figures/other/umap_107.pdf"),
            base_width = 2 * 89 * 0.039, base_height = 3)

g107_umaps <- cowplot::plot_grid(gumap1_107+ theme(legend.position = "none"), 
                                 gumap2_107 + theme(legend.position = "none"), 
                                 NULL, NULL,
                                 ncol = 2, align = "v", axis = "tb",
                                 rel_heights = c(1, 0.))

g107_vlns <- cowplot::plot_grid(
                             gnotch + ylim(c(0, 3)) + removexaxis, 
                             NULL,
                             gvegf + removexaxis,
                             NULL,
                             ghypoxia + removexaxis,
                             NULL,
                             ghif1a,
                             ncol = 1, align = "v", axis = "lr", 
                             rel_heights = c(1, -0.1, 1, -0.1,1, -0.1, 1.2))

(g107rna <- plot_grid(
          NULL,
          g107_umaps,
          NULL,
          g107_vlns,
          rel_widths = c(0.2, 2,0.05, 0.5),
          nrow = 1
          ))

```

```{r}
obj_009 <- readRDS(find_allfiles(".Rdata", patients = "009"))
obj_009 <- subset(obj_009, subset = clone_id_clone_acn_10kb != "0")

obj_009@meta.data$clone_id <- obj_009@meta.data$clone_id_clone_acn_10kb
#obj_009@meta.data$RHOJ <- as.vector(obj_009@assays$RNA$data["RHOJ",])
Idents(obj_009) <- "clone_id"
obj_009@meta.data$VIM <- as.vector(obj_009@assays$RNA@data["VIM",])
obj_009@meta.data$HIF1A <- as.vector(obj_009@assays$RNA@data["HIF1A",])
```

```{r, fig.height = 3}

print("EMT module")
gemt <- myrnaplot(obj_009, feature = EMT.module, 
          mycomparisons = list(c("E", "F")),
          myylab = "EMT")
print("EMT Hallmark")
gemt2 <- myrnaplot(obj_009, feature = HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION, 
          mycomparisons = list(c("E", "F")),
          myylab = "EMT")
print("VIM")
gVIM <- myrnaplot(obj_009, feature = VIM, 
          mycomparisons = list(c("E", "F")),
          myylab = "VIM")
print("JAKstat")
gjakstat <- myrnaplot(obj_009, feature = JAK.STAT.pathway, 
          mycomparisons = list(c("E", "F")),
          myylab = "JAK-STAT")
print("JAKstat 2")
gjakstat2 <- myrnaplot(obj_009, feature = HALLMARK_IL6_JAK_STAT3_SIGNALING, 
          mycomparisons = list(c("E", "F")),
          myylab = "JAK-STAT")

sphase <- obj_009@meta.data %>% 
  group_by(clone_id, Phase) %>% 
  summarize(n = n()) %>% 
  mutate(f = n / sum(n)) %>% 
  ggplot(aes(x = clone_id, y = f, fill = Phase)) +
  geom_col(size = 0.3, width = 0.3) +
  ylab("Fraction") +
  scale_fill_manual(values = c("firebrick3", "blueviolet", "darkgoldenrod2")) +
  xlab("")

print("G2M")
gG2m_009 <- myrnaplot(obj_009, feature = HALLMARK_G2M_CHECKPOINT, 
          mycomparisons = list( c("E", "F")),
          myylab = "G2M")

gumap1_009 <- DimPlot(obj_009, group.by =  "clone_id", cols = cp, alpha = 0.2, pt.size = 0.5, stroke.size = 0, raster = FALSE, shuffle = TRUE) + ggtitle("") +
  theme_void() +
  theme(legend.position = "bottom") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  guides(color=guide_legend(nrow=2, byrow=TRUE, override.aes = list(size=1)))  
libcols <- c("#A1C181", "#BBA0B2", "#D58936", "#1985A1" , "firebrick4", "yellow3", "magenta")
gumap2_009 <- DimPlot(obj_009, group.by =  "sample_short", cols = libcols, alpha = 0.2, pt.size = 0.5, stroke.size = 0, raster = FALSE, shuffle = TRUE) + ggtitle("") +
  theme_void() +
  theme(legend.position = "bottom", legend.text = element_text(size = 7)) +
  guides(color=guide_legend(nrow=2, byrow=TRUE, override.aes = list(size=1))) 
cowplot::plot_grid(gumap2_009, gumap1_009, ncol = 2, align = "hv", axis = "tb") %>% 
  save_plot(plot = ., filename = here("Figures/other/umap_009.pdf"),
            base_width = 2 * 89 * 0.039, base_height = 3)


g009_umaps <- cowplot::plot_grid(gumap1_009+ theme(legend.position = "none"), 
                                 gumap2_009 + theme(legend.position = "none"), 
                                 NULL, NULL,
                                 ncol = 2, align = "v", axis = "tb",
                                 rel_heights = c(1, 0.0))

g009_vlns <- cowplot::plot_grid(
                             gemt2 + ylim(c(NA, 0.1)) + removexaxis, 
                             NULL,
                             gVIM + removexaxis,
                             NULL,
                             gjakstat + removexaxis,
                             NULL,
                             sphase + theme(legend.position = "bottom"),
                             ncol = 1, align = "v", axis = "lr", 
                             rel_heights = c(1, -0.1, 1, -0.1, 1, -0.1, 1.3))

(g009rna <- plot_grid(
          NULL,
          g009_umaps,
          NULL,
          g009_vlns,
          rel_widths = c(0.2, 2,0.05, 0.55),
          nrow = 1
          ))
```

## Pathway heterogeneity

Here we show that there is considerable heteroegeneity in pathway activity between genomically defined clones.

```{r}
md <- fread(paste0(config$root, "/metadata/ovarian_cancer_metadata.csv"))
md$RNA_snn_res.0.1 <- paste0(md$RNA_snn_res.0.1 )
md$RNA_snn_res.0.2 <- paste0(md$RNA_snn_res.0.2 )
md$RNA_snn_res.0.3 <- paste0(md$RNA_snn_res.0.3 )

treealign <- fread(paste0(config$root, "/metadata/ovarian_cancer_treealign.csv"))
infercnvclusters <- fread(paste0(config$root, "/metadata/ovarian_cancer_infercnvclusters.csv"))

md <- left_join(md, treealign) %>% 
  left_join(infercnvclusters) %>% 
  replace_na(list(clone_id = "0", infercnv = "0"))


df <- md %>% 
  add_count(patient_id) %>% 
  filter(n > 500) %>% # at least 500 cells
  select(-n) %>% 
  mutate(cluster_id = clone_id) %>% 
  filter(cluster_id != "0") %>% 
  filter(cluster_id != "") %>% 
  add_count(patient_id, cluster_id) %>% 
  filter(n > 50) %>% # at least 50 cells per clone/cluster
  select(cluster_id, starts_with("HALL"), cell_id, patient_id) %>% 
  pivot_longer(starts_with("HALL")) %>% 
  group_by(patient_id, cluster_id, name) %>% 
  summarize(value = mean(value)) %>% 
  group_by(name) %>%
  #mutate(value = (value - mean(value)) / sd(value)) %>%
  ungroup() %>%
  group_by(patient_id, name) %>% 
  #summarise(x = var(value)) %>% 
  summarise(x_diff = max(value) - min(value), x_max = max(value), x_min = min(value),
            x_mean = mean(value), x_var = var(value)) %>% 
  group_by(name) %>% 
  mutate(x_ord = mean(x_diff)) %>% 
  arrange(desc(x_ord)) %>% 
  mutate(name = str_remove(name, "HALLMARK_")) %>% 
  ungroup() %>% 
  arrange(desc(x_diff)) %>% 
  mutate(ord = 1:n())

df$ord <- order(df$x_diff, decreasing = T)


g1 <- df %>% 
  ggplot(aes(x = fct_reorder(name, x_ord, .desc = T), y = x_diff)) +
  geom_violin(scale = "width", fill = "grey70", col = "grey70") + 
  geom_point(position = position_jitter(width = 0.1, height = 0.0), size = 0.1) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  ylab("Max inter-clone\nscore difference") +
  xlab("Pathway") +
  stat_summary(fun = "mean",
               position = position_dodge(width = 0.9),
            geom = "crossbar", 
            width = 0.5, 
            size = 0.3,
            col = "firebrick4")
```

## Make final figure

```{r, fig.height = 5, fig.width = 7}
source(here("src/plotting_utils.R"))
g009_vlns <- plot_grid(
                      cowplot::plot_grid(
                             gemt2 + removexaxis, 
                             NULL,
                             gVIM, ncol = 1, align = "v", axis = "lr", rel_heights = c(1, -0.1, 1.2)),
                      cowplot::plot_grid(
                             gjakstat + removexaxis,
                             NULL,
                             sphase + theme(legend.position = "none"), ncol = 1, align = "v", axis = "lr", rel_heights = c(1, -0.1, 1.2)),
                      ncol=2)

g009_1 <- get_clone_bar_plot("SPECTRUM-OV-009")  + theme(legend.position = "none")
g009rna <- plot_grid(
          NULL,
          plot_grid(g009_1, g009_umaps, ncol = 2, rel_widths = c(0.25, 1)),
          NULL,
          g009_vlns,
          rel_widths = c(0.05, 2,0.05, 1),
          nrow = 1
          )

g107_vlns <- plot_grid(
                      cowplot::plot_grid(
                             gnotch + ylim(c(0, 3)) + removexaxis, 
                             NULL,
                             gvegf, ncol = 1, align = "v", axis = "lr", rel_heights = c(1, -0.1, 1.2)),
                      cowplot::plot_grid(
                             ghypoxia + removexaxis,
                             NULL,
                             ghif1a, ncol = 1, align = "v", axis = "lr", rel_heights = c(1, -0.1, 1.2)),
                      ncol=2)
g107_1 <- get_clone_bar_plot("SPECTRUM-OV-107")  + theme(legend.position = "none")
g107rna <- plot_grid(
          NULL,
          plot_grid(g107_1, g107_umaps, ncol = 2, rel_widths = c(0.25, 1)),
          NULL,
          g107_vlns,
          rel_widths = c(0.05, 2,0.05, 1),
          nrow = 1
          )

gbottom <- plot_grid( g107rna, g009rna, ncol = 1)

plot_grid(g1 + theme_cowplot(font_size = 6, line_size = 0.25), 
          g107rna, g009rna, ncol = 1, rel_heights = c(1.5, 1,1)) %>% 
  save_plot(plot = ., filename = here("Figures/Fig5_scrna.pdf"),
            base_width = 2 * 89 * 0.039, base_height = 5)

plot_grid(g1 + theme_cowplot(font_size = 6, line_size = 0.25), 
          g107rna, g009rna, ncol = 1, rel_heights = c(1.5, 1,1))
```