---
title: "Figure 2"
author: "Marc J Williams"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    df_print: kable
    number_sections: yes
    toc: no
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(here)
source(here("src/setup.R"))
```

## Error rates

```{r}
svdf <- svs %>% 
  filter(clonality == "Clonal") %>% 
  mutate(mutation_type = "SV") %>% 
  select(target_idx, patient,Bamtype, mutation_type, type, Type, rearrangement_type,
         VAF.background, total_counts.background, alt_counts.background, alt_seq_reads.background, alt_span_reads.background) %>% 
  ungroup() %>% 
  arrange(target_idx) %>% 
  distinct()

svdf %>% filter(VAF.background > 0)

snvdf <- snvs %>% 
  filter(filter_out == FALSE) %>% 
  filter(T == 1 & clonality == "Clonal") %>% 
  mutate(mutation_type = "SNV") %>% 
  select(target_idx, patient,Bamtype, mutation_type, 
         VAF.background, total_counts.background, alt_counts.background) %>% 
  distinct()

snvdf %>% filter(VAF.background > 0 & Bamtype == "Duplex")


bind_rows(svdf, snvdf) %>% 
  group_by(Bamtype, mutation_type) %>% 
  summarise(med = median(VAF.background, na.rm = T), 
            mean = mean(VAF.background, na.rm = T), 
            lq = quantile(VAF.background, 0.25,na.rm = T),
            uq = quantile(VAF.background, 0.75,na.rm = T),
            tot = sum(total_counts.background, na.rm = T),
            alt = sum(alt_counts.background, na.rm = T),
            nevents = sum(VAF.background > 0, na.rm = T),
            totevents = n()) %>% 
  mutate(vaf2 = alt / tot) %>% 
  DT::datatable()
```

```{r}

bind_rows(svdf, snvdf) %>% 
  lm(VAF.background ~ Bamtype + mutation_type, data = .) %>% 
  summary(.)

cols <- c("#00A6A6", "#F4B266")
symnum.args <- list(cutpoints = c( 0.00, 0.001, 0.01, 0.05, 1), symbols = c("***", "**", "*", "ns"))

g2 <- bind_rows(svdf, snvdf) %>% 
  filter(!is.na(VAF.background)) %>% 
  mutate(Bamtype = ifelse(Bamtype == "Uncollapsed", "Uncorrected", Bamtype)) %>% 
  group_by(Bamtype, mutation_type) %>% 
  summarize(n = sum(alt_counts.background == 0, na.rm = T),
            ntot = dplyr::n(),
            frac0 = sum(alt_counts.background == 0, na.rm = T) / dplyr::n()) %>% 
  ggplot(aes(x = Bamtype, y = frac0, fill = mutation_type)) +
  geom_col(position = position_dodge(0.6), width = 0.5) +
  ylab("Fraction of mutations\nwith 0 background") +
  labs(fill = "") +
  scale_fill_manual(values = cols)  +
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  theme(legend.position = c(0.7, 0.92)) +
  xlab("")

lod <- bind_rows(svdf, snvdf) %>% 
  group_by(patient, Bamtype, mutation_type) %>% 
  summarise(alt_counts = sum(alt_counts.background, na.rm = T),
            total_counts = sum(total_counts.background, na.rm = T)) %>% 
  mutate(f = alt_counts / total_counts) %>% 
  mutate(Bamtype = ifelse(Bamtype == "Uncollapsed", "Uncorrected", Bamtype)) %>% 
  group_by(Bamtype, mutation_type) %>% 
  summarise(x = 2 * max(f, na.rm = T)) 

g3 <- bind_rows(svdf, snvdf) %>% 
  group_by(patient, Bamtype, mutation_type) %>% 
  summarise(alt_counts = sum(alt_counts.background, na.rm = T),
            total_counts = sum(total_counts.background, na.rm = T)) %>% 
  mutate(f = alt_counts / total_counts) %>% 
  mutate(Bamtype = ifelse(Bamtype == "Uncollapsed", "Uncorrected", Bamtype)) %>% 
  ggplot(aes(y = f, x = Bamtype, fill = mutation_type, col = mutation_type)) +
  geom_violin(scale = "width", position = position_dodge(1.0), alpha = 0.4, size = 0.2)  + 
  geom_point(position = position_jitterdodge(dodge.width = 0.9, jitter.width = 0.15), 
       aes(fill = mutation_type, col = mutation_type), size = 0.1, alpha = 0.8) +
  geom_boxplot(col = "white", position = position_dodge(1.0), linewidth = 0.25, width = 0.25, outlier.shape = NA, alpha = 0.75) +
  #geom_point(data = lod, aes(y = x),  shape = 17, fill = "black", position = position_dodge(width = 1.0)) +
  scale_fill_manual(values = cols) +
  scale_color_manual(values = cols, guide = FALSE) +
  labs(fill = "") +
  #scale_y_log10()
  #logyscale(sigma = 0.000001, limits = c(0, 1)) +
  scale_y_continuous(trans = scales::pseudo_log_trans(sigma = 0.000001, base = 10), 
                   breaks = c(0.0,  0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0),
                   labels = scales::trans_format("log10", scales::math_format(10^.x)),
                   limits = c(0, 0.01)) +
  ylab("Per patient error rate") +
  #theme(legend.position = "none") +
  ggpubr::stat_compare_means(label.y.npc = 0.9,method = "t.test",
  aes(label = paste0(..p.signif..)), size = 3, symnum.args = symnum.args,
  ) +
  xlab("") +
  scale_x_discrete(guide = guide_axis(angle = 45))

g3
```

```{r}
knitr::kable(lod)
```

```{r}
bind_rows(svdf, snvdf) %>% 
  filter(Bamtype %in% c("Simplex", "Duplex")) %>% 
  group_by(patient,  mutation_type) %>% 
  summarise(alt_counts = sum(alt_counts.background, na.rm = T),
            total_counts = sum(total_counts.background, na.rm = T)) %>% 
  mutate(f = alt_counts / total_counts) %>%
  group_by(mutation_type) %>% 
  summarise(x = 2 * max(f, na.rm = T), mean(total_counts)) 

```

```{r}
library(broom)
bind_rows(svdf, snvdf) %>% 
  group_by(Bamtype, mutation_type) %>% 
  nest() %>% 
  spread(key =mutation_type, value = data) %>% 
  mutate(
    t_test = map2(SNV, SV, ~{t.test(.x$VAF.background, .y$VAF.background,alternative = "greater") %>% tidy()}),
    SNV = map(SNV, nrow),
    SV = map(SV, nrow)
  ) %>% 
  unnest() %>% 
  DT::datatable(filter = "top")

bind_rows(svdf, snvdf) %>% 
  group_by(Bamtype, mutation_type) %>% 
  nest() %>% 
  spread(key =mutation_type, value = data) %>% 
  mutate(
    t_test = map2(SNV, SV, ~{wilcox.test(.x$VAF.background, .y$VAF.background, alternative = "greater") %>% tidy()}),
    SNV = map(SNV, nrow),
    SV = map(SV, nrow)
  ) %>% 
  unnest()  %>% 
  DT::datatable(filter = "top")

```

## Correlation TP53 and SV

```{r}
gtp53 <- purity %>% 
  filter(!str_detect(patient, "003|014")) %>% #no TP53 (014) or first timepoint not at diagnosis
  filter(timepoint == 1) %>% 
  ggplot(aes(x = tumorfraction_TP53, y = tumorfraction_ClonalSV)) +
  geom_point(shape = 16, size = 1.2, alpha = 0.5) +
  scale_x_continuous(trans = scales::pseudo_log_trans(sigma = 0.0001, base = 10), 
                 breaks = c(0.0,  0.001, 0.01, 0.1, 1.0),
                 labels = scales::trans_format("log10", scales::math_format(10^.x)),
                 limits = c(0, 1),
                 guide = guide_axis(angle = 0)) +
  scale_y_continuous(trans = scales::pseudo_log_trans(sigma = 0.0001, base = 10), 
                 breaks = c(0.0, 0.001, 0.01, 0.1, 1.0),
                 labels = scales::trans_format("log10", scales::math_format(10^.x)),
                 limits = c(0, 1)) +
  geom_abline(lty = 2, col = "firebrick") +
  annotate(geom = "text", label = "y=x", angle = 42, x = 0.0002, y = 0.00068, col = "firebrick4", size = 2.7) +
  xlab("TP53 derived tumour fraction") +
  ylab("Mean SV VAF") +
  ggpubr::stat_cor(aes(label = ..r.label..), size = 2.5,method = "pearson")
gtp53
```

```{r}
dat <- purity %>% 
  filter(!str_detect(patient, "003|014")) %>% 
  filter(timepoint == 1)
cor.test(dat$tumorfraction_TP53, dat$tumorfraction_ClonalSV, alternative = "two.sided", method = "pearson")

```

## VAF

```{r}
libs_to_keep <- purity %>% 
  group_by(patient) %>% 
  filter(timepoint == 1) %>% 
  pull(sample)

sv_table <- svs %>% 
  filter(alt_span_reads.background == 0 & alt_seq_reads.background == 0) %>% 
  filter(clonality == "Clonal") %>%  
  filter(sample_id %in% libs_to_keep) %>% 
  filter(bamtype %in% c("uncollapsed")) %>% 
  group_by(patient, target_idx, sample_id, days, timepoint) %>% 
  summarise(alt_counts = sum(alt_seq_reads + alt_span_reads), total_counts = sum(total_counts)) %>% 
  distinct() %>% 
  ungroup() %>% 
  mutate(VAF = alt_counts / total_counts) %>% 
  filter(total_counts > 100) %>% 
  select(patient, target_idx, sample_id, days, timepoint, VAF) %>% 
  mutate(type = "SV")

snv_table <- snvs %>% 
  filter(filter_out == FALSE) %>% 
  filter(clonality == "Clonal" | Hugo_Symbol == "TP53") %>% 
  filter(bamtype == "duplex") %>% 
  filter(sample %in% libs_to_keep) %>% 
  filter(VAF.background == 0) %>% 
  distinct() %>% 
  rename(sample_id = sample) %>% 
  select(patient, target_idx, sample_id, days, timepoint, VAF) %>% 
  mutate(type = "SNV")

tp53_table <- snvs %>% 
  filter(Hugo_Symbol == "TP53") %>% 
  filter(bamtype == "duplex") %>% 
  filter(sample %in% libs_to_keep) %>% 
  distinct() %>% 
  rename(sample_id = sample) %>% 
  select(patient, target_idx, sample_id, days, timepoint,VAF,) %>% 
  mutate(type = "SNV") %>% 
  mutate(ptid_short = str_remove(patient, "SPECTRUM-OV-"))

cols <- c("#00A6A6", "#F4B266")

gvaf <- bind_rows(sv_table %>% mutate(VAF = 1 * VAF), snv_table) %>% 
  mutate(ptid_short = str_remove(patient, "SPECTRUM-OV-")) %>% 
  filter(!ptid_short %in% c("065", "044", "003")) %>% #remove sampels from pilot which had v few snvs
  na.omit() %>% 
  ggplot(aes(x = ptid_short, y = VAF)) +
  geom_violin(scale = "width", aes(fill = type, col = type), alpha = 1.0, size = 0.2) +
  # ggrastr::geom_point_rast(position = position_jitterdodge(dodge.width = 0.9), 
  #          aes(fill = type, col = type), size = 0.1, alpha = 0.8,) +
  #geom_point(position = position_jitterdodge(dodge.width = 0.9), 
  #         aes(fill = type, col = type), size = 0.1, alpha = 0.8,) +
  geom_boxplot(col = "white",aes(fill = type, col = type), position = position_dodge(0.9), width = 0.25, outlier.shape = NA, linewidth = 0.15) +
  scale_y_continuous(trans = scales::pseudo_log_trans(sigma = 0.0001, base = 10), 
                                   breaks = c(0.0, 0.001, 0.01, 0.1, 1L),
                                   labels = scales::trans_format("log10", scales::math_format(10^.x)),
                                   limits = c(0, NA)) +
  xlab("") +
  ylab("VAF at baseline\n(truncal mutations)") +
  scale_x_discrete(guide = guide_axis(angle = 0)) +
  scale_fill_manual(values = cols) +
  scale_color_manual(values = cols) +
  theme( strip.background = element_blank()) +
  labs(fill = "", col = "")
 gvaf
```

## OV-107 plots


```{r}
dat_10kb <- read_allfiles(pattern = "_clone_copynumber_10kb.csv", "107") %>% 
  mutate(cell_id = clone_id) %>% 
  filter(mappability > 0.99)

bps_md <- read_allfiles(pattern = "breakpoints-metadata.csv.gz", "107") 

sv_to_plot <- bps_md %>% 
  filter(target_idx == "19_34107614")

gcn <- plotCNprofile(dat_10kb, 
              cellid = "A", 
              chrfilt = c("8", "19"), 
              ideogram = T,
              maxCN = 15,
              pointsize = 0.1,
              y_axis_trans = "squashy",
              SV = sv_to_plot,
              annotateregions = data.frame(chr = "19", start = 30300001),
              ) +
  theme_cowplot(font_size = 7, line_size = 0.25) +
  theme(legend.position = "none")
gcn
```

## Final figure

```{r}

gtopa <- plot_grid(NULL, gcn, NULL, ncol = 1,rel_heights = c(0.05, 1, 1))
gtop <- plot_grid(gtopa, NULL, ncol = 2, rel_widths = c(0.65,1), labels = c("a", "b"), label_size = 8)

gbottom <- plot_grid(NULL, 
                     g3 + theme(legend.position = "none"), 
                     NULL,
                     g2, 
                     gtp53, 
                     ncol = 5, axis = "tblr", align = "hv",
                     rel_widths = c(0.02, 1, 0.0, 1,1),
                       labels = c("d", "", "", "e", "f"), label_size = 8)

gbottom <- plot_grid(NULL, g3 + theme(legend.position = "none"), 
                     NULL,
          g2, gtp53, NULL,
          ncol = 6, axis = "tblr", align = "hv",
          rel_widths = c(1.2, 1, 0.0, 1,1, 0.02),
          labels = c("c", "d", "", "e", "f", ""), label_size = 8)


gbottom <- plot_grid(gtp53,
                     NULL,
                     g3 + theme(legend.position = "none"), 
                     NULL,
                     g2, 
                     NULL,
          ncol = 6, axis = "tblr", align = "hv",
          rel_widths = c(1, 1.2, 1, 0,1, 0.02),
          labels = c("c", "d", "e", "f", "", ""), label_size = 8)

gmiddle <- plot_grid(gvaf + theme(legend.position = "none"), 
                     labels = c("b"), label_size = 8)

gall <- plot_grid(gmiddle,
                  NULL,
                  gbottom, ncol = 1, rel_heights = c( 0.7, 0.05, 1),
                  label_size = 8)

save_plot(here("Figures/Fig2_svdetection.pdf"), 
          gall, base_width = 2 * 89 * 0.039, base_height = 2.5)

gall
```
